name: PluginSasha
version: '1.0-SNAPSHOT'
main: be.sasha.pluginsasha.PluginSasha
api-version: '1.21'
commands:
  spawn:
    description: Se téléporter au spawn du serveur
    usage: /spawn
  setspawn:
    description: Définir le spawn du serveur
    usage: /setspawn
  bag:
    description: Ouvrir son sac à dos
    usage: /bag
  annonce:
    description: Faire une annonce
    permission: annonce.use
    usage: /annonce <message>
  message:
    aliases: msg
    description: Envoyer un message privé à un joueur joueur
    usage: /msg <player> <message>
  help:
    description: Obtenir la liste des commandes du plugin
    usage: /help
  menu:
    description: Ouvrir le menu principal
    uage: /menu